### ISSUE TITLE
Deploy standalone eUPF in YC with external connectivity

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#372]
## Acceptance criteria

# Definition of done
- [x] eUPF deployed in a YC cloud
- [x] N4 interface is available for external SMF
- [x] N3 interface is available for external gNB

**Comment by mbaran0v** [comment]
eupf has been launched on compute instance via docker compose, see config here  https://github.com/edgecomllc/things-for-demo/blob/master/step3/manifests/docker-compose.yaml 

for this option, we also need a VPN link between the 5G core and the eupf instance if we use kubernetes for the 5G core. This is because eupf is trying to send a packet to the IP address of the GNB module.
